/*
 * @Author: shulu
 * @Date: 2023-12-18 15:48:21
 * @LastEditors: shulu
 * @LastEditTime: 2023-12-20 14:58:13
 * @Description: file content
 * @FilePath: /vue3-element-plus-admin/src/plugins/elementui.js
 */
import {
    ElAffix,
    ElAlert,
    //ElAside,
    ElAutocomplete,
    ElAvatar,
    ElBacktop,
    ElBadge,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElButton,
    ElButtonGroup,
    //ElCalendar,
    ElCard,
    ElCascader,
    ElCascaderPanel,
    // ElCarousel,
    // ElCarouselItem,
    ElCheckbox,
    ElCheckboxButton,
    ElCheckboxGroup,
    ElCol,
    //ElCollapse,
    //ElCollapseItem,
    ElColorPicker,
    ElConfigProvider,
    ElContainer,
    ElDatePicker,
    ElDescriptions,
    ElDescriptionsItem,
    ElDialog,
    ElDivider,
    //ElDrawer,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElEmpty,
    ElFooter,
    ElForm,
    ElFormItem,
    ElHeader,
    ElIcon,
    ElImage,
    ElInput,
    ElInputNumber,
    ElLink,
    //ElInfiniteScroll,
    ElLoading,
    ElMain,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElMessage,
    ElMessageBox,
    ElNotification,
    ElOption,
    ElOptionGroup,
    //ElPageHeader,
    ElOverlay,
    ElPagination,
    ElPopconfirm,
    ElPopover,
    ElPopper,
    //ElProgress,
    ElRadio,
    ElRadioButton,
    ElRadioGroup,
    //ElRate,
    ElRow,
    ElScrollbar,
    ElSelect,
    ElSelectV2,
    ElSlider,
    ElSpace,
    ElStatistic,
    //ElStep,
    //ElSteps,
    ElSubMenu,
    ElSwitch,
    ElTabPane,
    ElTable,
    ElTableColumn,
    ElTabs,
    ElTag,
    ElTimePicker,
    ElTimeSelect,
    //ElTimeline,
    //ElTimelineItem,
    ElTooltip,
    ElTransfer,
    ElTree,
    ElTreeSelect,
    ElTreeV2,
    ElUpload,
} from 'element-plus';
const components = [
    ElAffix,
    ElConfigProvider,
    ElSpace,
    ElScrollbar,
    ElCascader,
    ElCascaderPanel,
    ElAlert,
    ElAutocomplete,
    ElAvatar,
    ElBacktop,
    ElBadge,
    ElBreadcrumb,
    ElBreadcrumbItem,
    ElButton,
    ElButtonGroup,
    ElCard,
    // ElCarousel,
    // ElCarouselItem,
    ElCheckbox,
    ElCheckboxButton,
    ElCheckboxGroup,
    ElCol,
    ElColorPicker,
    ElContainer,
    ElDatePicker,
    ElDescriptions,
    ElDescriptionsItem,
    ElDivider,
    ElDialog,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElEmpty,
    ElFooter,
    ElForm,
    ElFormItem,
    ElHeader,
    ElIcon,
    ElImage,
    ElInput,
    ElInputNumber,
    ElLink,
    ElMain,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElOption,
    ElOptionGroup,
    ElOverlay,
    ElPagination,
    ElPopconfirm,
    ElPopover,
    ElPopper,
    ElRadio,
    ElRadioButton,
    ElRadioGroup,
    ElRow,
    ElSelect,
    ElSelectV2,
    ElSlider,
    ElSubMenu,
    ElSwitch,
    ElTabPane,
    ElTable,
    ElTableColumn,
    ElTabs,
    ElTag,
    ElTimePicker,
    ElTimeSelect,
    ElTooltip,
    ElTree,
    ElTreeV2,
    ElTreeSelect,
    ElTransfer,
    ElUpload,
    ElStatistic,
];

const plugins = [
    //ElInfiniteScroll,
    ElLoading,
    ElMessage,
    ElMessageBox,
    ElNotification,
];

export default (app) => {
    components.forEach((component) => {
        app.component(component.name, component);
    });
    plugins.forEach((plugin) => {
        app.use(plugin);
    });
};
